name: Snyk Code Scan

on:
  pull_request:
    branches:
      - main

jobs:
  snyk:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Snyk CLI
        uses: snyk/actions/setup@master  # Correct action tag

      - name: Authenticate with Snyk
        run: snyk auth ${{ secrets.SNYK_TOKEN }}

      - name: Run Snyk Code Analysis
        run: snyk code test --all-projects
