name: Snyk Code Scan

on:
  pull_request:
    branches:
      - main

jobs:
  snyk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: snyk/actions/setup@master
      - run: snyk auth ${{ secrets.SNYK_TOKEN }}
      - run: snyk test --all-projects
